# # # # # Error and Exception Terminilogy # # # # #
# Exception
# Throw and Catch
# The Call Stack
# Terminating and Non-Terminating Errors
# Swallowing an Exception


# # # # # Differences Betweeen Errors and Exceptions # # # # #
# Errors:
# Errors are returned as PowerShell Objects. Providing terminating and non-terminating errors
#
# Exceptions:
# Exceptions are created when normal error handling cannot handle the issue.
# Exceptions are typically non-terminating


# # # # # Terminating and Non-Terminating # # # # #
# Terminating
# The error generated by the script, functions, or commands, stop or halts the execution
#
# Non-Terminating
# Generated by internal commands. Normally automatically handled so the error doesnt
# terminate the execution of the pipeline


# # # # # Error Handling Approaches # # # # #
# Throw an Exception
# Write-Error
# -ErrorAction
# try { } / catch { }
# try { } / finally { }
# try { } / catch / finally { }



# # # # # Generating and Handling Errors # # # # #
# Generating an Error using "Throw"
function New-Error 
{
    Throw "This is an Error"    
}
New-Error
# Output:
# Line |
#   40 |      Throw "This is an Error"    
#      |      ~~~~~~~~~~~~~~~~~~~~~~~~    
#      | This is an Error

# Use Write-Error with -ErrorAction to Generate Error
Write-Error -Message "This is an Error" -ErrorAction Stop
Output:
# Write-Error: This is an Error


# Generating an Error using "Throw"
function New-Error1
{
    $number = 0
    for ($i = 1; $i -le 10; $i++)
    {
        Write-Host "The current number is: $i"
        Throw "This is another Error"    
        $number += $i
    }
}
New-Error1
# Output:
# Line |
#   63 |          Throw "This is another Error"
#      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#      | This is another Error



# # # # # The -ErrorAction Paramater Values # # # # #
# Continue       : Log's error,   then display error to console and continues processing
# Stop           : Log's error,   then display error to console and then terminates
# SilentContinue : Log's error,   NOT  display error and continues processing
# Ignore         : NOT log error, NOT  display error and continues processing

